### ISSUE TITLE
무지개 API

### ISSUE THREAD

**Issue by hyunjong-96** [TeamMascota/Mascota-Server#2]
## 목표
> 무지개 관련된 API
## 작업 상세 내용
- [x] #3
- [x] [Get] 무지개 이별할 동물 선택
- [x] [Get] 무지개 다리 멘트
- [x] [Get] 작가의 기록 시작
- [x] [Get] 최고의 순간
- [x] [Post] 작가의 말 - 에필로그
- [x] [Get] 무지개 서브 홈 화면
## 참고사항
뭔가 설명을 추가해야하는 경우? 이미지나 이런것들은 여기에 작성해주세요

**Comment by soleu** [comment]
뭔가 잘못누름..... 이거 뭐야....

**Comment by SumiKang** [comment]
ㅋㅋㅋㅋㅋㅋ닫았나바
